services:
  backend_bd:
    image: backend_bd
    build:
      context: .
      dockerfile: Backend_BD/Dockerfile

  infrastructure:
    image: infrastructure
    build:
      context: .
      dockerfile: Infrastructure/Dockerfile

